-- MySQL Script generated by MySQL Workbench
-- Thu Apr 10 13:09:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school_management_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school_management_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_management_schema` DEFAULT CHARACTER SET utf8 ;
USE `school_management_schema` ;

-- -----------------------------------------------------
-- Table `school_management_schema`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`School` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `name` VARCHAR(255) NOT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `contactEmail` VARCHAR(255) NULL DEFAULT NULL,
  `isActive` VARCHAR(45) NULL,
  `isActive` TINYINT(1) NULL DEFAULT 1,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Role` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `title` VARCHAR(100) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`User` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `username` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `tempPassword` VARCHAR(50) NULL,
  `schoolId` VARCHAR(36) NULL,
  `address` TEXT NULL,
  `phone` VARCHAR(10) NULL,
  `specialization` VARCHAR(100) NULL,
  `rollNumber` VARCHAR(5) NULL,
  `roleId` VARCHAR(36) NOT NULL,
  `parentEmail` VARCHAR(100) NULL,
  `isActive` TINYINT(1) NULL DEFAULT 1,
  `isTempPassword` TINYINT(1) NULL DEFAULT 1,
  `system_defined` TINYINT(1) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_school_idx` (`schoolId` ASC) VISIBLE,
  INDEX `fk_user_role_id_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_user_school`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_id`
    FOREIGN KEY (`roleId`)
    REFERENCES `school_management_schema`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`RefreshToken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`RefreshToken` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID',
  `token` VARCHAR(255) NOT NULL,
  `userId` VARCHAR(36) NOT NULL DEFAULT 'UUID',
  `expiresAt` DATE NOT NULL,
  `isRevoked` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_rToken_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Invite` (
  `senderId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `receiverId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_invite_receiver_id_idx` (`receiverId` ASC) VISIBLE,
  INDEX `fk_invite_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_invite_sender_id`
    FOREIGN KEY (`senderId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_invite_receiver_id`
    FOREIGN KEY (`receiverId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_invite_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Class` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `name` VARCHAR(155) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`TeacherClass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`TeacherClass` (
  `teacherId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `classId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_teacher_class_id_idx` (`classId` ASC) VISIBLE,
  INDEX `fk_teacher_id_idx` (`teacherId` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_class_id`
    FOREIGN KEY (`classId`)
    REFERENCES `school_management_schema`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_id`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Assignment` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `title` VARCHAR(150) NOT NULL,
  `description` TEXT NULL,
  `dueDate` DATE NULL,
  `teacherId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `classId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `schoolId` VARCHAR(36) NOT NULL,
  `fileURL` VARCHAR(500) NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_assignment_class_id_idx` (`classId` ASC) VISIBLE,
  INDEX `fk_assignment_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_assignment_class_id`
    FOREIGN KEY (`classId`)
    REFERENCES `school_management_schema`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignment_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`ClassSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`ClassSchedule` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `classId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `teacherId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `subject` VARCHAR(255) NOT NULL,
  `dayOfWeek` ENUM('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat') NOT NULL,
  `date` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_classSchedule_class_id_idx` (`classId` ASC) VISIBLE,
  INDEX `fk_classSchedule_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_classSchedule_class_id`
    FOREIGN KEY (`classId`)
    REFERENCES `school_management_schema`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classSchedule_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`ExamSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`ExamSchedule` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `classId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `schoolId` VARCHAR(36) NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `examDate` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `roomNo` VARCHAR(5) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_examSchedule_class_id_idx` (`classId` ASC) VISIBLE,
  INDEX `fk_examSchedule_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_examSchedule_class_id`
    FOREIGN KEY (`classId`)
    REFERENCES `school_management_schema`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examSchedule_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Event` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `date` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `classId` VARCHAR(36) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT 	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_event_class_id_idx` (`classId` ASC) VISIBLE,
  INDEX `fk_event_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_event_class_id`
    FOREIGN KEY (`classId`)
    REFERENCES `school_management_schema`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Permission` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `title` VARCHAR(150) NOT NULL,
  `userId` VARCHAR(36) NULL,
  `setterId` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_permission_id_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_permission_setter_id_idx` (`setterId` ASC) VISIBLE,
  CONSTRAINT `fk_user_permission_id`
    FOREIGN KEY (`userId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_permission_setter_id`
    FOREIGN KEY (`setterId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Experience` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `organization_name` VARCHAR(255) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `userId` VARCHAR(36) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experience_user_id_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_experience_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_experience_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experience_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Degree` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `title` VARCHAR(50) NOT NULL,
  `institute` VARCHAR(255) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `certificate` VARCHAR(500) NULL,
  `userId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_degree_user_id_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_degree_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Result` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `studentId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `teacherId` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `res_file` VARCHAR(500) NOT NULL,
  `grade` VARCHAR(3) NULL,
  `classId` VARCHAR(36) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_result_student_id_idx` (`studentId` ASC) VISIBLE,
  INDEX `fk_result_teacher_id_idx` (`teacherId` ASC) VISIBLE,
  INDEX `fk_result_class_id_idx` (`classId` ASC) VISIBLE,
  INDEX `fk_result_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_result_student_id`
    FOREIGN KEY (`studentId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_teacher_id`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_class_id`
    FOREIGN KEY (`classId`)
    REFERENCES `school_management_schema`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Attendance` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `studentId` VARCHAR(36) NOT NULL,
  `teacherId` VARCHAR(36) NOT NULL,
  `classScheduleId` VARCHAR(36) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendance_student_id_idx` (`studentId` ASC) VISIBLE,
  INDEX `fk_attendance_teacher_id_idx` (`teacherId` ASC) VISIBLE,
  INDEX `fk_attendance_class_id_idx` (`classScheduleId` ASC) VISIBLE,
  INDEX `fk_attendance_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_attendance_student_id`
    FOREIGN KEY (`studentId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_teacher_id`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_class_id`
    FOREIGN KEY (`classScheduleId`)
    REFERENCES `school_management_schema`.`ClassSchedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`Complaint` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `subject` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_complaint_user_id_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_complaint_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_complaint_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complaint_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_management_schema`.`NoticeBoard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_schema`.`NoticeBoard` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `notice` TEXT NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notice_user_id_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_notice_school_id_idx` (`schoolId` ASC) VISIBLE,
  CONSTRAINT `fk_notice_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `school_management_schema`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notice_school_id`
    FOREIGN KEY (`schoolId`)
    REFERENCES `school_management_schema`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
